# Generated by Django 3.1.8 on 2021-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(max_length=6)),
                ('surname', models.CharField(max_length=50)),
                ('other_name', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('parents', models.CharField(blank=True, max_length=40, null=True)),
                ('parents_contact', models.CharField(max_length=11)),
                ('number_of_sura_memorized', models.PositiveIntegerField(null=True)),
                ('organization_1', models.CharField(default='Tell us the name of the organization if the above is checked yes...', max_length=120)),
                ('organization_address_1', models.CharField(max_length=120)),
                ('organization_2', models.CharField(max_length=120)),
                ('organization_address_2', models.CharField(max_length=120)),
                ('organization_3', models.CharField(max_length=120)),
                ('organization_address_3', models.CharField(max_length=120)),
                ('position_held_1', models.CharField(default='If you have held any position in the above organization, please specify the position...', max_length=25, null=True)),
                ('position_held_2', models.CharField(default='If you have held any position in the above organization, please specify the position...', max_length=25, null=True)),
                ('position_held_3', models.CharField(default='If you have held any position in the above organization, please specify the position...', max_length=25, null=True)),
            ],
        ),
    ]
