# Generated by Django 3.1.8 on 2021-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='registration_number',
            field=models.IntegerField(),
        ),
    ]
