# Generated by Django 3.1.8 on 2021-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210504_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
