# Generated by Django 3.1.8 on 2021-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210504_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='organization_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='organization_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='organization_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='organization_address_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='organization_address_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='organization_address_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='position_held_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='position_held_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='position_held_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
